import { calcGst, round2 } from './accounting.js'

const findVendor = (vendors, partyName) => vendors.find(
  (vendor) => vendor.name.trim().toLowerCase() === (partyName || '').trim().toLowerCase(),
)

// A vendor-wise, invoice-wise register of this period's bills and debit
// notes (purchase returns) - meant to be checked line by line against the
// GSTR-2B you download from the GST portal (Returns Dashboard -> GSTR-2A/
// 2B). That statement is generated by the government from what your
// vendors themselves reported in their own GSTR-1, so it can't be built
// from this app's own data - what this register is for is catching the
// gaps: a bill here with no matching row on your 2B usually means that
// vendor hasn't filed yet (so the ITC on it isn't actually available to
// claim this period), or filed it with a different amount/GSTIN.
export const buildPurchaseRegister = (bills, debitNotes, vendors, items, from, to) => {
  const periodBills = bills.filter((bill) => !bill.voided && (!from || bill.date >= from) && (!to || bill.date <= to))
  const periodNotes = debitNotes.filter((note) => (!from || note.date >= from) && (!to || note.date <= to))

  const billRows = periodBills.map((bill) => ({
    vendorName: bill.partyName,
    vendorGstin: findVendor(vendors, bill.partyName)?.gstin || '',
    number: bill.number,
    date: bill.date,
    rate: Number(bill.gstPercent) || 0,
    taxable: bill.taxable,
    cgst: bill.cgst,
    sgst: bill.sgst,
    igst: bill.igst,
    total: bill.total,
  }))

  const noteRows = periodNotes.map((note) => ({
    vendorName: note.partyName,
    vendorGstin: findVendor(vendors, note.partyName)?.gstin || '',
    number: note.number,
    date: note.date,
    taxable: -note.taxable,
    cgst: -note.cgst,
    sgst: -note.sgst,
    igst: -note.igst,
    total: -note.total,
  }))

  const hsnByCode = new Map()
  periodBills.forEach((bill) => {
    (bill.items || []).forEach((line) => {
      const taxable = round2((Number(line.qty) || 0) * (Number(line.rate) || 0))
      if (taxable <= 0) return
      const code = items.find((item) => item.id === line.itemId)?.hsnSac || 'NA'
      const gst = calcGst(taxable, bill.gstPercent, bill.interState)
      const existing = hsnByCode.get(code) || { code, qty: 0, taxable: 0, cgst: 0, sgst: 0, igst: 0 }
      existing.qty = round2(existing.qty + (Number(line.qty) || 0))
      existing.taxable = round2(existing.taxable + taxable)
      existing.cgst = round2(existing.cgst + gst.cgst)
      existing.sgst = round2(existing.sgst + gst.sgst)
      existing.igst = round2(existing.igst + gst.igst)
      hsnByCode.set(code, existing)
    })
  })

  const totals = [...billRows, ...noteRows].reduce((acc, row) => ({
    taxable: round2(acc.taxable + row.taxable),
    cgst: round2(acc.cgst + row.cgst),
    sgst: round2(acc.sgst + row.sgst),
    igst: round2(acc.igst + row.igst),
    total: round2(acc.total + row.total),
  }), { taxable: 0, cgst: 0, sgst: 0, igst: 0, total: 0 })

  const unmatchedCount = periodBills.filter((bill) => !findVendor(vendors, bill.partyName)).length

  return {
    bills: billRows,
    debitNotes: noteRows,
    hsn: [...hsnByCode.values()].sort((a, b) => a.code.localeCompare(b.code)),
    totals,
    unmatchedCount,
  }
}
